### ISSUE TITLE
Encryption breaks CP/M build

### ISSUE THREAD

**Issue by danielgaskell** [skx/lighthouse-of-doom#37]
In the CP/M version, the initial Z80 instructions should translate to

$0100: CALL $0D21 ; bios_init
$0D21: RET

...but in fact $0D21 is inside the encrypted zone and hasn't been decrypted yet, so what CP/M actually executes is

$0100: CALL #0D21 ; bios_init
$0D21: CALL #D00F

...which jumps off into never-never land. Amazingly, this actually works on most emulators/systems, because #D00F typically just contains a lot of NOP opcodes and the program will eventually hit a RET and find its way back to the correct place. But this is obviously not guaranteed and will crash on many systems. (The unencrypted version works as intended.)

[This extremely obscure bug report has been brought to you by me trying to figure out why this game runs in most emulators but crashes under my own in-progress CP/M compatibility layer for SymbOS.]

**Comment by skx** [comment]
Now you point it out this is obviously wrong, thanks for the bug-report.  And thanks even more for using my game as a  test at all!  (I've always thought the number of people who'd a) find and b) play this would be less than ten!)

I guess the solution is obvious, to move the call to bios_init just after the decryption routine.  I'll test that today/tomorrow, unless you beat me to it.

I'm sorry for making the testing more difficult for you, but thanks again for the report.

**Comment by danielgaskell** [comment]
No problem! It was a relief to find out that the bug wasn't in my own code, and I figured you might enjoy knowing that someone cared. :-)
