### ISSUE TITLE
Crash when answering no to play again.

### ISSUE THREAD

**Issue by t00** [skx/lighthouse-of-doom#44]
Just thought I might share this issue, not sure if it is emulator related.
![image](https://github.com/skx/lighthouse-of-doom/assets/1933165/1c424bc3-bc9f-41b6-bb1b-9cbd4e32e0e7)

**Comment by skx** [comment]
Thanks for the report, I wonder if I've left something on the stack which shouldn't be present.

I've been aware for a while, as a similar thing happens with CP/M exiting, but I should fix it for neatness:

```
>quit
You said 'QUIT' so we terminate!

You've played 00001 turns.

Play again? (y/n)n
[binaryu rubbish]
w#z>w#>
w#>frodo ~/Repos/github.com/skx/lighthouse $
```
